# Generated by Django 3.0.6 on 2020-05-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('task', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
