# Generated by Django 3.0.6 on 2020-05-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('ToDo', 'ToDO'), ('Do', 'Do'), ('Done', 'Done')], default='ToDo', max_length=4),
        ),
    ]
