# Generated by Django 3.0.6 on 2020-05-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200526_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('Done', 'Done'), ('ToDo', 'ToDO'), ('Do', 'Do')], default='ToDo', max_length=4),
        ),
    ]
