# Generated by Django 3.0.6 on 2020-05-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200526_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('Done', 'Done'), ('Do', 'Do'), ('ToDo', 'ToDo')], max_length=4),
        ),
    ]
