# Generated by Django 3.0.6 on 2020-05-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200528_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('ToDo', 'ToDo'), ('Do', 'Do'), ('Done', 'Done')], default='ToDo', max_length=4),
        ),
    ]
